### ISSUE TITLE
Source code of ndnlitesupport-debug.aar

### ISSUE THREAD

**Issue by yoursunny** [gujianxiao/NDN-IoT-Android#1]
It’s unclear where’s the source code of `ndnlitesupport-debug.aar`library. It’s necessary to add source code link and build instructions for this file.

**Comment by gujianxiao** [comment]
Thanks for pointing out the issue. In fact, we plan to merge the source code of  `ndnlitesupprort-debug` library into this repository. As for now, you can check the library via this [link](https://github.com/peurpdapeurp/ndn-lite-android-support-library), which has all source codes and building instruction. We will do the merging work ASAP. Thanks.

**Comment by peurpdapeurp** [comment]
Thank you for pointing this out; the merging of the ndnlitesupport library into the application has been done.
