### ISSUE TITLE
How to get an interest from the board?

### ISSUE THREAD

**Issue by Heath68** [gujianxiao/NDN-IoT-Android#2]
In the example you've provided,android got interest for certificate of device once sign on process completed, but now I want to get an interest from board for other use,and show parameter carried by it, what should I do?How to trigger the on interest function to show details of an received interest?

**Comment by peurpdapeurp** [comment]
There is a getApplicationParameters function defined in Interest.java of the jndn library (https://github.com/named-data/jndn/blob/master/src/net/named_data/jndn/Interest.java), it is around line 370.
